<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4472" started-at="2017-09-20T14:22:37Z" finished-at="2017-09-20T14:22:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4472" started-at="2017-09-20T14:22:37Z" finished-at="2017-09-20T14:22:41Z">
      <class name="com.org.test.TestFail">
        <test-method status="PASS" signature="launchBrower()[pri:0, instance:com.org.test.TestFail@a097cc]" name="launchBrower" is-config="true" duration-ms="26415" started-at="2017-09-20T19:52:10Z" finished-at="2017-09-20T19:52:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrower -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.org.test.TestFail@a097cc]" name="test1" duration-ms="3063" started-at="2017-09-20T19:52:37Z" finished-at="2017-09-20T19:52:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected text: 'Communications Overvie' did not match with actual text: 'Communications Overview' expected [Communications Overview] but found [Communications Overvie]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected text: 'Communications Overvie' did not match with actual text: 'Communications Overview' expected [Communications Overview] but found [Communications Overvie]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.org.test.TestFail.test1(TestFail.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.org.test.TestFail@a097cc]" name="test2" duration-ms="1394" started-at="2017-09-20T19:52:40Z" finished-at="2017-09-20T19:52:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="closeBrower()[pri:0, instance:com.org.test.TestFail@a097cc]" name="closeBrower" is-config="true" duration-ms="274" started-at="2017-09-20T19:52:41Z" finished-at="2017-09-20T19:52:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrower -->
      </class> <!-- com.org.test.TestFail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
